/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.okstate.frames;

import edu.okstate.entities.*;
import edu.okstate.executables.*;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author CIVE Administrator
 */
public class ProjectDetails extends javax.swing.JFrame {

    DefaultListModel projectsMainModel = new DefaultListModel();
    DefaultListModel projectsSubModel = new DefaultListModel();
    List<ProjectDataFull> projectDataAll;
    List<ProjectDataFull> projectDataAllNew;
    int INDEX;
    boolean flag = true;

    /**
     * Creates new form Project_Details
     */
    public ProjectDetails() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\CIVE Administrator\\eclipse-workspace\\CPM-Software\\src\\main\\resources\\osulogo.png"));

    }

    public ProjectDetails(String projectDescription) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\CIVE Administrator\\eclipse-workspace\\CPM-Software\\src\\main\\resources\\osulogo.png"));
        //List<ProjectDataAll> projectDataAll;
        projectsMainModel.clear();
        projectDataAll = GetProjectData.getProjectData(projectDescription);
        if (projectDataAll.isEmpty()) {
            System.out.println("List is empty*******************************************");
        } else {
            System.out.println("LENGTH OF THE LIST RECIEVED FROM GETPROJECTDATA******************************************* " + projectDataAll.size());
            for (ProjectDataFull p : projectDataAll) {
                add(p.getActivityName(),p.getActivityLevel());
            }
        }
    }

    private void add(String name, int level) {

        mainActivityList.setModel(projectsMainModel);
        mainActivityList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        if(level == 1)
            projectsMainModel.addElement("*"+name);
        else
            projectsMainModel.addElement(" "+name);
    }

    private void add1(String name) {

        subActivityList.setModel(projectsSubModel);
        subActivityList.setEnabled(false);
        if (flag == true) {
            projectsSubModel.addElement("*" + name);
            flag = false;
        } else {
            projectsSubModel.addElement(" "+name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mainActivityList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        subActivityList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comments = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        techDetails = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        unit = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        avgProdRate = new javax.swing.JTextField();
        duration = new javax.swing.JTextField();
        durationOverride = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        backToProjectHeaderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Project Details");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mainActivityList.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                mainActivityListComponentAdded(evt);
            }
        });
        mainActivityList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mainActivityListFocusGained(evt);
            }
        });
        mainActivityList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainActivityListMouseClicked(evt);
            }
        });
        mainActivityList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                mainActivityListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(mainActivityList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane4.setViewportView(subActivityList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        comments.setColumns(20);
        comments.setRows(5);
        comments.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                commentsFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(comments);

        techDetails.setColumns(20);
        techDetails.setRows(5);
        techDetails.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                techDetailsFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(techDetails);

        jLabel2.setText("Additional Technical Details");

        jLabel1.setText("Comments");

        jLabel3.setText("Unit");

        jLabel4.setText("Quantity");

        jLabel5.setText("Avg Prod Rate");

        jLabel6.setText("Duration");

        jLabel7.setText("Duration Override");

        unit.setEnabled(false);
        unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitActionPerformed(evt);
            }
        });

        quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityFocusLost(evt);
            }
        });
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityKeyTyped(evt);
            }
        });

        avgProdRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                avgProdRateFocusLost(evt);
            }
        });

        durationOverride.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                durationOverrideFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(duration, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(avgProdRate)
                    .addComponent(unit)
                    .addComponent(durationOverride)
                    .addComponent(quantity))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(avgProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(durationOverride, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        saveButton.setText("Save Changes");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        backToProjectHeaderButton.setText("Back to Project Header");
        backToProjectHeaderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToProjectHeaderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backToProjectHeaderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backToProjectHeaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToProjectHeaderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToProjectHeaderButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backToProjectHeaderButtonActionPerformed

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitActionPerformed

    private void mainActivityListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_mainActivityListValueChanged

    }//GEN-LAST:event_mainActivityListValueChanged

    private void mainActivityListComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_mainActivityListComponentAdded
        // TODO add your handling code here:
        System.out.println("THE COMPONENT HAS BEEN ADDED TO THE LIST****************************************");
    }//GEN-LAST:event_mainActivityListComponentAdded

    private void mainActivityListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mainActivityListFocusGained
        // TODO add your handling code here:
        System.out.println("LIST HAS GAINED THE FOCUS****************************************");
    }//GEN-LAST:event_mainActivityListFocusGained

    private void mainActivityListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainActivityListMouseClicked
        // TODO add your handling code here:
        System.out.println("MOUSE HAS BEEN CLICKED ONCE IN THE LIST****************************************");
        projectsSubModel.clear();

        int index = mainActivityList.getSelectedIndex();
        INDEX = index;
        System.out.println("[+++++++++++++++++++++++++++++++++++++++++++++++]");
        System.out.println(projectDataAll.get(0).toString());
        //int index1 = subActivityList.getSelectedIndex();

        if (projectDataAll.get(index).getActivityLevel() == 1) {
            do {
                add1(projectDataAll.get(index).getActivityName());
                index = index + 1;

                quantity.setEnabled(false);
                avgProdRate.setEnabled(false);
                duration.setEnabled(false);
                durationOverride.setEnabled(false);

                comments.setEnabled(false);
                techDetails.setEnabled(false);

                unit.setText("--");
                quantity.setText("0.0");
                avgProdRate.setText("0.0");
                duration.setText("0.0");
                durationOverride.setText("0.0");

                comments.setText("");
                techDetails.setText("");

            } while (projectDataAll.get(index).getActivityParent() != 0);
        } else {

            flag = true;

            quantity.setEnabled(true);
            avgProdRate.setEnabled(true);
            duration.setEnabled(true);
            durationOverride.setEnabled(true);

            comments.setEnabled(true);
            techDetails.setEnabled(true);

            unit.setText(projectDataAll.get(index).getActivityUnit());
            quantity.setText(Double.toString(projectDataAll.get(index).getQuantity()));
            avgProdRate.setText(Double.toString(projectDataAll.get(index).getAvgProdRate()));
            duration.setText(Double.toString(projectDataAll.get(index).getDuration()));
            durationOverride.setText(Double.toString(projectDataAll.get(index).getDurationOverride()));

            comments.setText(projectDataAll.get(index).getComments());
            techDetails.setText(projectDataAll.get(index).getTechDetails());
        }
    }//GEN-LAST:event_mainActivityListMouseClicked

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_quantityActionPerformed

    private void quantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_quantityKeyTyped

    private void quantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityFocusLost
        // TODO add your handling code here:
        System.out.println("THE QUANTITY VALUE " + quantity.getText() + " HAS BEEN SAVED FOR INDEX " + INDEX + " ");
        projectDataAll.get(INDEX).setQuantity(Double.parseDouble(quantity.getText()));
        duration.setText(Double.toString(Double.parseDouble(quantity.getText()) / Double.parseDouble(avgProdRate.getText())));
        projectDataAll.get(INDEX).setDuration(Double.parseDouble(duration.getText()));
        System.out.println("THE DURATION VALUE " + duration.getText() + " HAS BEEN SAVED FOR INDEX " + INDEX + " ");
    }//GEN-LAST:event_quantityFocusLost

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        projectDataAll = DeleteFullRecord.deleteFullRecord(projectDataAll);
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void avgProdRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_avgProdRateFocusLost
        // TODO add your handling code here:
        projectDataAll.get(INDEX).setAvgProdRate(Double.parseDouble(avgProdRate.getText()));
    }//GEN-LAST:event_avgProdRateFocusLost

    private void durationOverrideFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_durationOverrideFocusLost
        // TODO add your handling code here:
        projectDataAll.get(INDEX).setDurationOverride(Double.parseDouble(durationOverride.getText()));
    }//GEN-LAST:event_durationOverrideFocusLost

    private void commentsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_commentsFocusLost
        // TODO add your handling code here:
        projectDataAll.get(INDEX).setComments(comments.getText());
    }//GEN-LAST:event_commentsFocusLost

    private void techDetailsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_techDetailsFocusLost
        // TODO add your handling code here:
        projectDataAll.get(INDEX).setTechDetails(techDetails.getText());
    }//GEN-LAST:event_techDetailsFocusLost

    /**
     * @param args the command line arguments
     */
    public static void toProjectDetailsFrame(String projectHeader) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectDetails(projectHeader).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avgProdRate;
    private javax.swing.JButton backToProjectHeaderButton;
    private javax.swing.JTextArea comments;
    private javax.swing.JTextField duration;
    private javax.swing.JTextField durationOverride;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList mainActivityList;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton saveButton;
    private javax.swing.JList subActivityList;
    private javax.swing.JTextArea techDetails;
    private javax.swing.JTextField unit;
    // End of variables declaration//GEN-END:variables

}
